[package]
name = "docker-deep-clean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_docker = "0.1.1"
serde = "1.0.152"
serde_json = "1.0.93"
shiplift = "0.7.0"
tokio = "1.25.0"
